### ISSUE TITLE
Make use of proxies to intercept properties access and delegate to Falcor

### ISSUE THREAD

**Issue by jean-morissette** [greim/ng-falcor#14]
In order to improve readability of our code, we are wondering if we could make use of proxies to intercept access to property and delegate it to your library under the hood. 

That way, the client of your library could manipulate JS objects as if they were all in local memory, using standard notation `foo.bar.baz` instead of using the falcor path notation.

What do you think about this proposal?

**Comment by greim** [comment]
I think it's a really interesting idea. The reason I haven't pursued it myself is because proxies are a bit limited at the moment for browser support, and are one of the few things that can't be transpiled. So it's off the table for my current app unfortunately. That said, I'd totally love to see some experiments along these lines!

Also, side note, getters and setters have much better support, and I've added `ngf.object()` as a way to make use of them. Not as flexible as proxies, but still useful.

I'll close this issue, but please feel free to continue conversation :)
